---
# tasks file for roles/install-gitlab

- name: Update packages list
  apt:
    update_cache: true
  become: yes
  register: result_apt_update
  changed_when: false

- name: Install prerequisites packages
  apt:
    pkg:
    - curl
    - openssh-server
    - ca-certificates 
    - perl
    - postfix
  become: yes
  register: result_install_packages
  when: result_apt_update.failed == false

- name: Download Gitlab installation script
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    dest: /tmp/script_gitlab.sh
    mode: '0500'
  become: yes
  register: result_dl_gitlab_script
  when: result_install_packages.failed == false
  changed_when: false

- name: Run Gitlab installation script
  shell: /tmp/script_gitlab.sh
  become: yes
  register: result_run_gitlab_script
  when: result_dl_gitlab_script.failed == false
  changed_when: false


- name: Install Gitlab CE package
  shell: EXTERNAL_URL="http://gitlab.example.com" apt-get install gitlab-ce
  become: yes
  register: result_install_gitlab
  when: result_run_gitlab_script.failed == false
  changed_when: false

- name: Read initial_root_password file
  shell: "cat /etc/gitlab/initial_root_password | grep Password:"
  become: yes
  register: read_root_passwd
  when: result_install_gitlab.failed == false
  changed_when: false


- name: Display root initial password
  debug:
    var: read_root_passwd.stdout_lines
  when: result_install_gitlab.failed == false

- name: Remove Gitlab installation script file
  file:
    path: /tmp/script_gitlab.sh
    state: absent
  become: yes
  when: read_root_passwd.failed == false